name: shopware6
recipe: lamp
config:
  php: '8.1'
  composer_version: '2.0.12'
  webroot: public
  database: mysql:5.7
  xdebug: false
  services:
    database:
      portforward: true
    appserver:
      build_as_root:
        - curl -sL https://deb.nodesource.com/setup_14.x | bash -
        - apt update -y -q && apt install -q -y nodejs jq
      portforward: 9998
    redis-session:
      type: redis
      persist: true
    redis-cache:
      type: redis
      persist: false
    pma:
      type: phpmyadmin
      hosts:
        - database
  proxy:
    pma:
      - pma-shopware6.lndo.site
tooling:
  sw:
    service: appserver
    cmd: "php bin/console"
  npm:
    service: appserver
    cmd: "npm"
  build:
    service: appserver
    cmd: "/bin/bash /app/bin/build-js.sh"
  build-storefront:
    service: appserver
    cmd: "/bin/bash /app/bin/build-storefront.sh"
  watch:
    service: appserver
    cmd: "/bin/bash /app/bin/watch-storefront.sh"
